Lesson2
poncik-87/test-guru pull request #1
Opened 2021-06-26 07:33 UTC by poncik-87

2021-06-26 15:22 UTC, BubuntuClu requested changes

2021-06-26 15:22 UTC, BubuntuClu commented on config/initializers/application_version.rb
> +  version = '0.0.1'
Версия приложения начинается не с этих цифр. Как получить версию? Какой код надо вызвать?

2021-06-27 12:59 UTC, poncik-87 commented on config/initializers/application_version.rb
> +  version = '0.0.1'
не понял вопрос про "какой код надо вызвать", версию поправил

2021-06-27 18:02 UTC, BubuntuClu commented on config/initializers/application_version.rb
> +  version = '0.0.1'
ну вот ты написал код, который устанавливает версию приложения.

дальше допустим ты делаешь различные деплои своего приложения и чтобы с главной страницы ты мог посмотреть какая версия сейчас развернута на продакшене, можно в скрытое поле страницы вывести версию приложения. как вызвать твой код, чтобы он вернул текущую версию приложения?

2021-06-27 18:02 UTC, BubuntuClu commented on config/initializers/application_version.rb
> +  version = '0.0.1'
в консоле `rails c`какую команду ввести?

2021-06-27 19:52 UTC, poncik-87 commented on config/initializers/application_version.rb
> +  version = '0.0.1'
теперь понял. поправил на константу, теперь версию можно получить через. `TestGuru::VERSION`

2021-06-28 08:20 UTC, merged